name: demo_project
description: ''
version: 0.0.1
author: matthew+public_demo@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demoproject
  parentArtefactID: matthewpublicdemoprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-04-18 12:55:59'
pipelines:
  pipelines/demo_pipeline:
    name: demo_pipeline
    description: ''
    author: matthew+public_demo@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-04-18 12:55:59'
    datasets:
      inputs:
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: ''
    author: matthew+public_demo@prophecy.io
    createdAt: '2024-04-18 12:56:40'
    mode: batch
    physicalDatasets:
      databricks-demo:
        fabricId: 10584
        datasetType: File
        description: ''
        author: matthew+public_demo@prophecy.io
        createdAt: '2024-04-18 12:56:40'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-04-18 12:55:59'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-04-18T12:55:59.646422Z'
  name: plibMaven
  version: 7.1.88
  createdAt: '2024-04-18T12:55:59.646422Z'
  type: plibMaven
- modifiedAt: '2024-04-18T12:55:59.646422Z'
  name: plibPypi
  version: 1.8.15
  createdAt: '2024-04-18T12:55:59.646422Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-04-18 12:55:52'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.6
    isDefault: true
    author: null
    createdAt: '2024-04-18 12:55:52'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
